name: $(moduleName)

parameters:
- name: versioningOption
  displayName: Default publish version
  type: string
  default: patch
  values:
  - patch
  - minor
  - major
- name: uiCustomVersion
  displayName: -OR- Custom publish version
  type: string
  default: '-'
- name: removeDeployment
  displayName: Remove resources post-deployment
  type: boolean
  default: true

variables:
- template: /Modules/.global/global.variables.yml
- name: moduleName
  value: vm-windows

trigger:
  batch: true
  branches:
    include:
    - main
    - master 
  paths:
    include:
    - Modules/.global/*
    - Modules/vm-windows/*
    exclude:
    - Modules/vm-windows/readme.md
    
stages:
- stage: Validation
  jobs:
  - template: /Modules/.global/pipelineTemplates/pipeline.jobs.validate.yml
    parameters:
      deploymentBlocks:
      - path: $(parametersPath)/parameters.json

- stage: Deployment
  dependsOn: Validation
  condition: succeeded('Validation')
  jobs:
  - template: /Modules/.global/pipelineTemplates/pipeline.jobs.deploy.yml
    parameters:
      deploymentBlocks:
      - path: $(parametersPath)/parameters.json

- stage: Publishing
  dependsOn: Deployment
  condition: succeeded('Deployment')
  jobs:
  - template: /Modules/.global/pipelineTemplates/pipeline.jobs.deploy.yml
    parameters:
      deploymentBlocks:
      - path: $(parametersPath)/parameters.json

- stage: Removal
  condition: and(succeededOrFailed(), eq( '${{ parameters.removeDeployment }}', 'true'))
  dependsOn: Deployment
  jobs:
  - template: /Modules/.global/pipelineTemplates/pipeline.jobs.remove.yml